import { audioFiles } from 'assets'
import * as model from 'model/model'
import { Vector3 } from 'three'



export const initialScene: model.Scene = {
  viewerCameraStart: {
    position: new Vector3(0, 0, 0),
    orientation: {
      yaw: 0,
      pitch: 0,
    },
  },
  soundSources: [{
    name: 'Kick',
    position: new Vector3(2,0.5,1),
    orientation: {
      yaw: 70,
      pitch: 30,
    },
    coneInnerAngle: 70,
    coneOuterAngle: 90,
    coneOuterGain: 0,
    refDistance: 5,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_1_Kick,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Snare',
    position: new Vector3(4,0.5,1),
    orientation: {
      yaw: -180,
      pitch: 20,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_2_Snare,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Clap',
    position: new Vector3(3.5,0.5,1),
    orientation: {
      yaw: -180,
      pitch: 20,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_3_Clap,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Perc',
    position: new Vector3(3,0.5,1),
    orientation: {
      yaw: -180,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_4_Perc,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Hat',
    position: new Vector3(2.5,0.5,1),
    orientation: {
      yaw: -180,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_5_Hat,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Cymbal',
    position: new Vector3(2,0.5,1),
    orientation: {
      yaw: -180,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_6_Cymbal,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Bass',
    position: new Vector3(1.5,0.5,1),
    orientation: {
      yaw: -180,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_9_Bass,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Pad1',
    position: new Vector3(1,0.5,1),
    orientation: {
      yaw: -180,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_10_Pad1,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Sub',
    position: new Vector3(0.5,0.5,1),
    orientation: {
      yaw: -180,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_11_Sub,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Noise',
    position: new Vector3(-0.5,0.5,1),
    orientation: {
      yaw: 0,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_12_Noise,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Chimes',
    position: new Vector3(-1,0.5,1),
    orientation: {
      yaw: 0,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_13_Chimes,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Pad2',
    position: new Vector3(-1.5,0.5,1),
    orientation: {
      yaw: 0,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_14_Pad2,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }, {
    name: 'Pad3',
    position: new Vector3(-2,0.5,1),
    orientation: {
      yaw: 0,
      pitch: 25,
    },
    coneInnerAngle: 30,
    coneOuterAngle: 60,
    coneOuterGain: 0,
    refDistance: 3,
    maxDistance: 15,
    level: 1,
    soundClip: audioFiles.song.track_15_Pad3,
    speed: 1,
    start: 0,
    stop: 1,
    convolution: 'none',
  }],
}